### ISSUE TITLE
library not found for -ldsn.failure_detector

### ISSUE THREAD

**Issue by duanmeng** [Microsoft/rDSN#12]
# Description
I tried to make the counter example in tutorials::SingleNode in $rdsn/tutorials/counter/build but encounter a link error that no libdsn.failure_detector in $rdsn/tutorial/counter/build/lib or $rdsn/lib but no lib dir in neither of them.
At last I found the lib dir in $rdsn/mybuild which I created during the installation process following the tutorial::install.
macduanmatoMacBook-Pro:~ macduan$ find . -name libdsn.*
./work/rdsn/mybuilddir/lib/libdsn.core.a
./work/rdsn/mybuilddir/lib/libdsn.dev.a
./work/rdsn/mybuilddir/lib/libdsn.failure_detector.a
./work/rdsn/mybuilddir/lib/libdsn.replication.a
./work/rdsn/mybuilddir/lib/libdsn.replication.clientlib.a
./work/rdsn/mybuilddir/lib/libdsn.replication.meta_server.a
./work/rdsn/mybuilddir/lib/libdsn.tools.common.a
./work/rdsn/mybuilddir/lib/libdsn.tools.simulator.a

# Reproduce Steps
1. Follow step 1.3 tutorials::SingleNode
2. cmake and make -j in $RDSN/tutorial/counter/build

# Error Log
macduanmatoMacBook-Pro:counter macduan$ pwd
/Users/macduan/work/rdsn/tutorial/counter
macduanmatoMacBook-Pro:counter macduan$ cd build/
macduanmatoMacBook-Pro:build macduan$ make
Linking CXX executable bin/counter/counter
ld: warning: directory not found for option '-L/Users/macduan/work/rdsn/tutorial/counter/build/lib'
ld: warning: directory not found for option '-L/Users/macduan/work/rdsn/lib'
ld: library not found for -ldsn.failure_detector
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/counter/counter] Error 1
make[1]: *** [CMakeFiles/counter.dir/all] Error 2
make: *** [all] Error 2

**Comment by imzhenyu** [comment]
Hi,
This problem could be caused by NOT installing the libraries before trying the tutorial. Without install, the /lib dir is not well prepared, i.e., the library paths in the generated Makefile is decided by the location of dsn.cg.sh/.bat, where ```dir(dsn.cg.sh)/../lib``` is created by installation process.

Thanks,
Zhenyu

**Comment by imzhenyu** [comment]
Another case is that you did install it (as you said above), but the wrong ```dsn.cg.sh``` is called. You probably want to call the installed ```dsn.cg.sh``` instead of the one pulled from github.

**Comment by duanmeng** [comment]
I used $rDSN/bin/dsg.cg.sh and I suppose it is the installed dsg.cg.sh.
I copy $rDSN/mybuild/lib to $rDSN and make in $rDSN/tutorials/counter/build and success.
BTW my env is os x yosemite

**Comment by imzhenyu** [comment]
Unfortunately this not. The installed one should be located at the place where you place the header files as well as libraries and tools, when you call ```make install```.

**Comment by duanmeng** [comment]
I get it thanks.
