### ISSUE TITLE
Looking for a deeper understanding (unable to post to rdsn-support@googlegroups.com)

### ISSUE THREAD

**Issue by bswtzr** [Microsoft/rDSN#120]
First off, great work !!!

I'm using dsn_cli_register to invoke rpc calls from the console to my replicated, server-r, via a non-replicated server-nr. cli_handler wasn't on a worker thread so I used dsn_mimic_app. That requires running client-app-nr for no purpose other than to provide it's name to dsn_mimic_app. Is there another way to enter a worker? 

I hit an issue calling server-r from server-nr. server-r wasn't receiving calls until I ran a client-app-r that did nothing but create an unused client...should that be required?

Can multiple replication apps be registered/run in the same assembly?

PS: I experimented with cli_app.cpp - a single console for all nodes...very cool.

**Comment by imzhenyu** [comment]
@bswtzr, thx for the interest. Since we want to control all the non-determinism, we need to ensure all application logic running in rDSN controlled threads. As for the issue u raised, we have been considering automatically starting a default app to run them instead of asking developers to issue an explicit dsn-mimic-app. That work item is in the list. If you are interested, welcome to contribute the implementation(pull request to imzhenyu/rdsn for auto-test and latest version), or if u think it stops your further work, let us know and we will prioritize the item and finish it in short time.

**Comment by imzhenyu** [comment]
Multiple replicated apps can run in the same assembly. What's missing now is a command to meta server to register multiple apps. Replication server already supports this.

**Comment by imzhenyu** [comment]
@bswtzr, we now have the solution done for your problem. Please check at https://github.com/imzhenyu/rDSN/issues/33 . It is not yet merged into Microsoft/rDSN, but you can get it from imzhenyu/rDSN for the time being.

**Comment by bswtzr** [comment]
@imzhenyu I was hoping to spend more time here but got involved in other work. I've attached a simple app built with your latest rdsn code that calls server-r from server-nr as detailed in my initial post. server_r is a badly ported counter_service from your tutorial but good enough for this purpose. Entering add/read commands from the console usually results in a timeout using nativerun or fastrun but the simulator works ok. Maybe I doing something wrong? You'll need to avoid stepping into the code...a debugger side-effect allows it to run properly.
[repro.zip](https://github.com/Microsoft/rDSN/files/69261/repro.zip)

**Comment by bswtzr** [comment]
@imzhenyu, I was able to get this working by using the [replication] settings from simple_kv. I've attached the latest code as I also updated counter_server_impl to match simple_kv.server.impl.
[repro.zip](https://github.com/Microsoft/rDSN/files/70006/repro.zip)

**Comment by imzhenyu** [comment]
Thanks @bswtzr  You may want to submit a pull request for updating counter_server_impl if you want:)
