### ISSUE TITLE
compiling issue:error: expected ')' before 'PRId64'

### ISSUE THREAD

**Issue by lihuixian001** [Microsoft/rDSN#197]
I met a compiler problem, but I don't know how to solve it ....

`rdsn/src/plugins_ext/rDSN.dist.service/src/fd/failure_detector/failure_detector.cpp:535:57: error: expected ')' before 'PRId64'`

**Comment by lihuixian001** [comment]
i solve this problem  by adding   the following two lines of code to   service_api_c.h 
```
#define __STDC_FORMAT_MACROS
#include <inttypes.h>
```

**Comment by shengofsun** [comment]
are you using windows or linux?

**Comment by lihuixian001** [comment]
centos 7 , gcc version 4.8.5

**Comment by linmajia** [comment]
No such issue on Ubuntu 14.04 with gcc 4.8.4.
BTW: we should use PRIu64 since time is uint64_t.

**Comment by linmajia** [comment]
1. lihuixian001, you'd better add #include <cinttypes> in failure_detector.cpp instead of modifying service_api_c.h 
2. This may be due to another header (native_aio_provider.linux.h?) already includes <inttypes.h> without defining __STDC_FORMAT_MACROS. We will investigate this issue.
