### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wangchengqun** [Microsoft/rDSN#201]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe”已退出，代码为 1。 [D:\rDSN\rDSN\builddbg\ext\thrift\thrift.vcxproj]

**Comment by linmajia** [comment]
Would you please send us your development environment information and detailed build output?
