### ISSUE TITLE
build error: suggest explicit braces to avoid ambiguous ‘else’

### ISSUE THREAD

**Issue by huahang** [microsoft/rDSN#219]
I get a compile error:

/home/huahang/src/rdsn/src/core/src/clientlet.test.cpp: In lambda function:
/home/huahang/src/rdsn/src/core/src/clientlet.test.cpp:117:16: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]
             if (ERR_OK == ec)

**Comment by linmajia** [comment]
@huahang , thank you very much for the feedback. Which C++ compiler and version are you using?

**Comment by linmajia** [comment]
Fixed by PR #223 .
