### ISSUE TITLE
BSD support

### ISSUE THREAD

**Issue by thinkwing** [Microsoft/rDSN#4]
Hi，
Wish to be provided on BSD  i.e. freebsd.

**Comment by imzhenyu** [comment]
Hi Thinkwing,

Compilation should be supported already, see [here](https://github.com/Microsoft/rDSN/wiki/Installation#mac-os-x-yosemite-with-apple-llvm-version-610).  We do have a known issue that the file operations may not work well sometimes, and we don't have enough time digging into it yet. It is great if you are interested in trying it. Considering rDSN is extensible to [integrate new aio providers](https://github.com/Microsoft/rDSN/wiki/Tutorial:-Plugin-A-New-Network-Implementation), if you are not satisfied with the default providers, feel free to implement your own and we are very glad if you can contribute it back to rDSN to benefit the other projects atop of rDSN:)

Thanks,
Zhenyu

**Comment by imzhenyu** [comment]
I'll close this issue now; let us know when you have more issues.

**Comment by imzhenyu** [comment]
Hi Thinkwing,

Just realized my previous answer is wrong  - Not quite familiar with FreeBSD and thought Mac has the FreeBSD. We don't have a pure FreeBSD in hand yet, but we will see when we get a chance. Meanwhile, I'm also wondering if you can try it and see what are the problems - I guess most of the code is portable and only minor things need to be changed.

Thanks,
Zhenyu

**Comment by imzhenyu** [comment]
Hi Thinkwing, 

FreeBSD is now [supported](https://github.com/Microsoft/rDSN/commit/2b7f118830caeceec29c36b6a4e799abe21830ed).

Thanks,
Zhenyu
