### ISSUE TITLE
sample cmakelists.txt

### ISSUE THREAD

**Issue by prabcs** [Microsoft/rDSN#5]
hi,

could you please provide a sample CMakeLists.txt?

As per the install steps mentioned here for Ubuntu: https://github.com/Microsoft/rDSN/wiki/Installation, I'm unable to do this step: cmake .. -DCMAKE_INSTALL_PREFIX=/opt/rdsn

Thanks

**Comment by imzhenyu** [comment]
We cannot re-produce the issue you have. The CMakeLists.txt is at the root of the source tree. Can you paste the error messages so we may help?

**Comment by prabcs** [comment]
Hi,

Thanks for your response. I was not in the directory where CMakeLists.txt
could be found. I've located it now.

Regards,
Prabhjot

On Tue, Jun 2, 2015 at 5:47 AM, Zhenyu Guo <notifications@github.com> wrote:

> We cannot re-produce the issue you have. The CMakeLists.txt is at the root
> of the source tree. Can you paste the error messages so we may help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/rDSN/issues/5#issuecomment-107751542>.
>



-- 
---------------------------------------------------------
"There are only 10 types of people in the world: Those who understand
binary, and those who don't"

**Comment by imzhenyu** [comment]
Good. Enjoy~
