### ISSUE TITLE
nucleus, ever heard of pied piper

### ISSUE THREAD

**Issue by pancho-villa** [Microsoft/rDSN#6]
Hey guys, have you seen this thing by [Pied Piper](http://www.piedpiper.com/)? These guys got a crazy 5.2 Weissman score on loss less video compression! Insane! But word on the street is that they're working on robust distributed networks. Maybe you should just [acquire them.](http://en.wikipedia.org/wiki/Embrace,_extend_and_extinguish)

**Comment by imzhenyu** [comment]
Hi Pancho, I guess we are just not competing with them:) Thanks for your interest though.
