### ISSUE TITLE
/usr/local/include is not added to include path of rdsn in OS X Yosemite 

### ISSUE THREAD

**Issue by duanmeng** [Microsoft/rDSN#7]
# Reproduce Steps
1. follow the installation step in mac os x yosemite part of tutorials
2. mkdir $RDSN/mybuilddir; cd mybuilddir; cmake .. -DCMAKE_INSTALL_PREFIX=/opt/rdsn
3. sudo make install

# Error Message
fatal error: 'boost/shared_ptr.hpp' file not found

# My Analysis
1. boost/shared_ptr.hpp is indeed in /usr/local/include of my mac
2. it works fined in ubuntu 1404 LTS
3. it seems /usr/local/include is not add to the rdsn project's include path

# My Workaround
1. add "include_directories(/usr/local/include" in function dsn_setup_include_path in $RDSN/bin/dsn.cmake
2. sudo make install and it works fine

However IMHO they are neither root cause nor solution, I do not understand those var in dsn.cmake and how are they assigned/set.

**Comment by imzhenyu** [comment]
Hi duanmeng, 

Appreciate your great bug report! We don't have a Mac in hand, but we suspect it is highly possible that your Homebrew is not installed in the default directory. We will try later once we get access to a Mac. Meanwhile, you may also try cmake options like ```INCLUDEDIR="c:\boost_1_57_0" -DBOOST_LIBRARYDIR="c:\boost_1_57_0\lib64-msvc-12.0" ``` to see whether it works.

Thanks,
Zhenyu

**Comment by duanmeng** [comment]
Hi Zhengyu,

"-DBOOST_INCLUDEDIR=/usr/local/include" works!
And "BOOST_INCLUDEDIR:PATH=/usr/local/include" is inserted into $RDSN/mybuilddir/CMakeCache.txt.

Thanks
DuanMeng

**Comment by imzhenyu** [comment]
Great to hear it works! :) Let us know if you have more issues~
