### ISSUE TITLE
replication_service_app::start doesn't use working_dir set in config.ini

### ISSUE THREAD

**Issue by bswtzr** [Microsoft/rDSN#98]
error_code replication_service_app::start(int argc, char** argv)
{
    replication_options opts;
    opts.initialize();
// FIXME
//  opts.working_dir = std::string("./") + argv[0];

    _stub = new replica_stub();
    _stub->initialize(opts);
    _stub->open_service();
    return ERR_OK;
}

**Comment by imzhenyu** [comment]
Thanks, @bswtzr. We're looking into this.

**Comment by imzhenyu** [comment]
@bswtzr, the bug should now be fixed. Please update and try. Thank you.
